# Generated by Django 3.1.1 on 2020-10-14 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 11, 4, 7, 93172, tzinfo=utc)),
        ),
    ]
