# Generated by Django 3.1.1 on 2020-10-14 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_postbook_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 14, 59, 25, 821331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postbook',
            name='page_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
