# Generated by Django 3.1.1 on 2020-10-15 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0003_auto_20201014_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 8, 28, 20, 653607, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postbook',
            name='isbn_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='postbook',
            name='language',
            field=models.CharField(max_length=3),
        ),
    ]
